### ISSUE TITLE
installing plone.app.widgets breaks recurrence widget

### ISSUE THREAD

**Issue by enfold-josh** [plone/plone.formwidget.recurrence#13]
I have a Plone 4.3.2 instance with the following packages:

plone.app.contenttypes = 1.1b2
plone.app.event = 1.2
plone.formwidget.recurrence = 1.2
plone.app.widgets = 1.5.0

Without plone.app.widgets installed the recurrence widget works fine. If I install plone.app.widgets then the recurrence widget doesn't display. This is because plone.app.widgets deprecates ++resource++plone.app.jquerytools.dateinput.js and the recurrence widget js calls $.tools.dateinput.localize which is no longer defined.

If I move the dateinput js file back to the default bundle then the recurrence widget displays. However, the popup no longer includes the part to add and remove occurrences. This is because the recurrence javascript fails to get the start date.

**Comment by jensens** [comment]
outdated
